spring.application.name=webchat
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/webchat}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.flyway.enabled=true
jwt.secret=${JWT_SECRET:38bab2288bb09f4a1a20300047ea5a0ee5981adac1b0f8f6796470649db7245f}
jwt.access.expiration-time=${JWT_ACESS_EXPIRATION_TIME:3600000}
jwt.refresh.expiration-time=${JWT_REFRESH_EXPIRATION_TIME:86400000}